srp-3/inc-13
paramonies/ya-shortener pull request #13
Opened 2022-03-29 14:16 UTC by paramonies

2022-03-31 10:04 UTC, blattaria7 commented on internal/store/pg_store.go
> +	ConstraintViolationError = errors.New("original url conflict")
формат названий ошибок в гошке `ErrFoo` - нужно переименовать в `ErrConstraintViolation`

2022-03-31 10:04 UTC, blattaria7 commented on internal/store/pg_store.go
> +	ConstraintViolationError = errors.New("original url conflict")
формат названий ошибок в гошке `ErrFoo` - нужно переименовать в `ErrConstraintViolation`

2022-03-31 10:06 UTC, blattaria7 commented on internal/handlers/handlers.go
> +			rep.Set(fmt.Sprintf("%d", id), URL, cookie.Value)
метод `Set` возвращает ошибку, надо ее проверить

2022-03-31 10:06 UTC, blattaria7 commented on internal/handlers/handlers.go
> +			rep.Set(fmt.Sprintf("%d", id), URL, cookie.Value)
метод `Set` возвращает ошибку, надо ее проверить

2022-03-31 10:36 UTC, blattaria7 requested changes
Код написан хорошо, но работу не могу принять, так как не работают go vet, автотесты и нет юнит-тестов  :( 

Что нужно сделать:
1.  Исправить ошибки из логов `go vet test`
2. Покрыть сервис логами в STDOUT, так логи программы смогут выводиться в джобах автотестов
3. Посмотреть на то, что ругается каждый автотест, сравнить что у тебя есть и что требуется. Например второй инкремент проверяет покрытие кода тестами => нужно добавить юнит-тесты

2022-04-19 00:05 UTC, blattaria7 requested changes
К сожалению не могу принять работу, так как не работают автотесты из-за ошибок.
Необходимо поработать над кодом сервера и применением паттернов DI. 
Также вижу по автотестам, что также не хватает покрытия юнитами.

2022-05-06 13:48 UTC, lugingf requested changes
Во вкладке checks видны упавшие тесты по большому количеству инкрементов. Их надо все поправить.

2022-05-06 15:15 UTC, lugingf approved these changes

2022-05-21 19:25 UTC, merged